import React from 'react';
import Card from '../components/Card';

const ConceptifyPage: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto space-y-8">
      <div className="text-center">
        <h1 className="text-4xl font-extrabold text-slate-900 dark:text-white tracking-tight">Conceptify</h1>
        <p className="mt-3 text-lg text-slate-500 dark:text-slate-400">Key concepts and formulas used in SoftMetrics, explained simply.</p>
      </div>

      <Card className="p-6">
        <h2 className="text-2xl font-bold text-brand-primary mb-3">Net Present Value (NPV)</h2>
        <p className="text-slate-700 dark:text-slate-300 mb-4">
          Net Present Value (NPV) is a method used to determine the current value of all future cash flows generated by a project, including the initial capital investment. It is widely used in capital budgeting to establish which projects are likely to turn the greatest profit. A positive NPV indicates a profitable investment, while a negative NPV suggests it may result in a net loss.
        </p>
        <h3 className="text-lg font-semibold text-slate-900 dark:text-white mb-2">Formula</h3>
        <div className="bg-slate-200 dark:bg-slate-900 p-4 rounded-md text-center">
          <code className="text-lg text-cyan-600 dark:text-cyan-400 font-mono">NPV = Σ [ CFₜ / (1 + r)ᵗ ] - C₀</code>
        </div>
        <ul className="list-disc list-inside mt-4 text-slate-700 dark:text-slate-300 space-y-1">
          <li><span className="font-semibold text-slate-800 dark:text-white">CFₜ</span>: Cash flow at time t.</li>
          <li><span className="font-semibold text-slate-800 dark:text-white">r</span>: The discount rate.</li>
          <li><span className="font-semibold text-slate-800 dark:text-white">t</span>: The time period.</li>
          <li><span className="font-semibold text-slate-800 dark:text-white">C₀</span>: The initial investment (at time 0).</li>
        </ul>
      </Card>

      <Card className="p-6">
        <h2 className="text-2xl font-bold text-brand-primary mb-3">Present Value of an Annuity Factor (PVAF)</h2>
        <p className="text-slate-700 dark:text-slate-300 mb-4">
          The Annuity Factor is a value you can multiply by a single cash flow in a series of equal cash flows to find their total present value. It's a shortcut used to calculate the present value of an ordinary annuity, saving you from discounting each cash flow individually.
        </p>
        <h3 className="text-lg font-semibold text-slate-900 dark:text-white mb-2">Formula</h3>
        <div className="bg-slate-200 dark:bg-slate-900 p-4 rounded-md text-center">
          <code className="text-lg text-cyan-600 dark:text-cyan-400 font-mono">PVAF = (1 - (1 + r)⁻ⁿ) / r</code>
        </div>
        <ul className="list-disc list-inside mt-4 text-slate-700 dark:text-slate-300 space-y-1">
          <li><span className="font-semibold text-slate-800 dark:text-white">r</span>: The interest rate per period.</li>
          <li><span className="font-semibold text-slate-800 dark:text-white">n</span>: The number of periods.</li>
        </ul>
      </Card>
      
      <Card className="p-6">
        <h2 className="text-2xl font-bold text-brand-primary mb-3">Constructive Cost Model (COCOMO)</h2>
        <p className="text-slate-700 dark:text-slate-300 mb-4">
          COCOMO is a procedural software cost estimation model. The basic model computes software development effort (and cost) as a function of program size, expressed in estimated thousands of lines of code (KLOC). The calculation depends on the project type: Organic, Semidetached, or Embedded.
        </p>
        <h3 className="text-lg font-semibold text-slate-900 dark:text-white mb-2">Formulas</h3>
        <div className="bg-slate-200 dark:bg-slate-900 p-4 rounded-md text-left space-y-2">
          <code className="block text-md text-cyan-600 dark:text-cyan-400 font-mono">Effort (E) = a * (KLOC)ᵇ Person-Months</code>
          <code className="block text-md text-cyan-600 dark:text-cyan-400 font-mono">Development Time (D) = c * (E)ᵈ Months</code>
        </div>
        <p className="mt-4 text-slate-700 dark:text-slate-300">
            The constants (a, b, c, d) vary based on the project type, which reflects the complexity and team experience.
        </p>
      </Card>

      <Card className="p-6">
        <h2 className="text-2xl font-bold text-brand-primary mb-3">Inflation</h2>
        <p className="text-slate-700 dark:text-slate-300 mb-4">
          Inflation is the rate at which the general level of prices for goods and services is rising, and subsequently, the purchasing power of currency is falling. The inflation calculator helps you understand how much money you would need in the future to have the same buying power as a certain amount of money today.
        </p>
        <h3 className="text-lg font-semibold text-slate-900 dark:text-white mb-2">Formula</h3>
        <div className="bg-slate-200 dark:bg-slate-900 p-4 rounded-md text-center">
          <code className="text-lg text-cyan-600 dark:text-cyan-400 font-mono">Future Value = Present Value * (1 + r)ⁿ</code>
        </div>
        <ul className="list-disc list-inside mt-4 text-slate-700 dark:text-slate-300 space-y-1">
          <li><span className="font-semibold text-slate-800 dark:text-white">Present Value</span>: The initial amount of money.</li>
          <li><span className="font-semibold text-slate-800 dark:text-white">r</span>: The annual inflation rate.</li>
          <li><span className="font-semibold text-slate-800 dark:text-white">n</span>: The number of years.</li>
        </ul>
      </Card>
      
      <Card className="p-6">
        <h2 className="text-2xl font-bold text-brand-primary mb-3">Indian Income Tax (New Regime AY 2025-26)</h2>
        <p className="text-slate-700 dark:text-slate-300 mb-4">
          This refers to the default tax system for individuals in India for the financial year 2024-25. The calculation is based on income slabs, with different tax rates applying to different portions of the income.
        </p>
        <h3 className="text-lg font-semibold text-slate-900 dark:text-white mb-2">Tax Slabs</h3>
        <ul className="list-disc list-inside mt-4 text-slate-700 dark:text-slate-300 space-y-1">
          <li><span className="font-semibold text-slate-800 dark:text-white">Up to ₹3,00,000:</span> No tax</li>
          <li><span className="font-semibold text-slate-800 dark:text-white">₹3,00,001 to ₹6,00,000:</span> 5%</li>
          <li><span className="font-semibold text-slate-800 dark:text-white">₹6,00,001 to ₹9,00,000:</span> 10%</li>
          <li><span className="font-semibold text-slate-800 dark:text-white">₹9,00,001 to ₹12,00,000:</span> 15%</li>
          <li><span className="font-semibold text-slate-800 dark:text-white">₹12,00,001 to ₹15,00,000:</span> 20%</li>
          <li><span className="font-semibold text-slate-800 dark:text-white">Above ₹15,00,000:</span> 30%</li>
        </ul>
        <h3 className="text-lg font-semibold text-slate-900 dark:text-white mt-4 mb-2">Key Points</h3>
        <ul className="list-disc list-inside mt-2 text-slate-700 dark:text-slate-300 space-y-1">
          <li><span className="font-semibold text-slate-800 dark:text-white">Standard Deduction:</span> A flat deduction of ₹50,000 is available for salaried individuals.</li>
          <li><span className="font-semibold text-slate-800 dark:text-white">Tax Rebate (Sec 87A):</span> If your taxable income (after deductions) is ₹7,00,000 or less, you pay zero tax.</li>
          <li><span className="font-semibold text-slate-800 dark:text-white">Health & Education Cess:</span> An additional 4% is levied on the calculated income tax amount.</li>
        </ul>
      </Card>
    </div>
  );
};

export default ConceptifyPage;