import React from 'react';
import Card from '../components/Card';

const HelpPage: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto space-y-8">
      <div className="text-center">
        <h1 className="text-4xl font-extrabold text-slate-900 dark:text-white tracking-tight">Help & Concepts</h1>
        <p className="mt-3 text-lg text-slate-500 dark:text-slate-400">Understand the financial metrics behind softMetrics.</p>
      </div>

      <Card className="p-6">
        <h2 className="text-2xl font-bold text-brand-primary mb-3">Present Value of an Annuity Factor (PVAF)</h2>
        <p className="text-slate-700 dark:text-slate-300 mb-4">
          The Annuity Factor is a value you can multiply by a single cash flow in a series of equal cash flows to find their total present value. It's a shortcut used to calculate the present value of an ordinary annuity, saving you from discounting each cash flow individually.
        </p>
        <h3 className="text-lg font-semibold text-slate-900 dark:text-white mb-2">Formula</h3>
        <div className="bg-slate-200 dark:bg-slate-900 p-4 rounded-md text-center">
          <code className="text-lg text-cyan-600 dark:text-cyan-400 font-mono">PVAF = (1 - (1 + r)⁻ⁿ) / r</code>
        </div>
        <ul className="list-disc list-inside mt-4 text-slate-700 dark:text-slate-300 space-y-1">
          <li><span className="font-semibold text-slate-800 dark:text-white">r</span>: The interest rate per period.</li>
          <li><span className="font-semibold text-slate-800 dark:text-white">n</span>: The number of periods.</li>
        </ul>
      </Card>

      <Card className="p-6">
        <h2 className="text-2xl font-bold text-brand-primary mb-3">Net Present Value (NPV)</h2>
        <p className="text-slate-700 dark:text-slate-300 mb-4">
          Net Present Value (NPV) is a method used to determine the current value of all future cash flows generated by a project, including the initial capital investment. It is widely used in capital budgeting to establish which projects are likely to turn the greatest profit. A positive NPV indicates a profitable investment, while a negative NPV suggests it may result in a net loss.
        </p>
        <h3 className="text-lg font-semibold text-slate-900 dark:text-white mb-2">Formula</h3>
        <div className="bg-slate-200 dark:bg-slate-900 p-4 rounded-md text-center">
          <code className="text-lg text-cyan-600 dark:text-cyan-400 font-mono">NPV = Σ [ CFₜ / (1 + r)ᵗ ] - C₀</code>
        </div>
        <ul className="list-disc list-inside mt-4 text-slate-700 dark:text-slate-300 space-y-1">
          <li><span className="font-semibold text-slate-800 dark:text-white">CFₜ</span>: Cash flow at time t.</li>
          <li><span className="font-semibold text-slate-800 dark:text-white">r</span>: The discount rate.</li>
          <li><span className="font-semibold text-slate-800 dark:text-white">t</span>: The time period.</li>
          <li><span className="font-semibold text-slate-800 dark:text-white">C₀</span>: The initial investment (at time 0).</li>
        </ul>
      </Card>
    </div>
  );
};

export default HelpPage;